CREATE TABLE property (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier VARCHAR(32) NOT NULL,
    supplier_property_code VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_property_supplier_code UNIQUE (supplier, supplier_property_code)
);

CREATE TABLE room_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL,
    supplier_room_type_code VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    max_occupancy INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_room_type_property FOREIGN KEY (property_id) REFERENCES property (id),
    CONSTRAINT uk_room_type_property_code UNIQUE (property_id, supplier_room_type_code)
);
