CREATE TABLE mapping_supplier_readiness (
    supplier VARCHAR(32) NOT NULL PRIMARY KEY,
    ready BOOLEAN NOT NULL,
    last_success_at TIMESTAMP
);

CREATE TABLE mapping_unmapped_code_backoff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier VARCHAR(32) NOT NULL,
    supplier_property_code VARCHAR(128) NOT NULL,
    supplier_room_type_code VARCHAR(128) NOT NULL,
    step INTEGER NOT NULL,
    next_eligible_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_backoff_code UNIQUE (supplier, supplier_property_code, supplier_room_type_code)
);
